language: ruby

rvm:
  - 2.4
  - 2.6

gemfile:
  - gemfiles/Gemfile.rails50
  - gemfiles/Gemfile.latest-release
  - gemfiles/Gemfile.rails-edge

env:
  - DB=mysql2
  - DB=postgresql

jobs:
  exclude:
    - rvm: 2.4
    - gemfiles/Gemfile.rails-edge

services:
  - memcache
  - mysql
  - postgresql

sudo: false

before_script:
  - mysql -e 'create database identity_cache_test'
  - psql -c 'create database identity_cache_test;' -U postgres

cache: bundler

matrix:
  exclude:
    - rvm: 2.2.6
      gemfile: gemfiles/Gemfile.rails-edge

notifications:
  email: false
