language: ruby

rvm:
  - 2.4
  - 2.6
  - 2.7

gemfile:
  - gemfiles/Gemfile.rails52
  - gemfiles/Gemfile.latest-release
  - gemfiles/Gemfile.rails-edge

env:
  - DB=mysql2
  - DB=postgresql
  - DB=mysql2 ADAPTER=memcached

jobs:
  exclude:
    - rvm: 2.4
      gemfile: gemfiles/Gemfile.rails-edge
    - rvm: 2.4
      gemfile: gemfiles/Gemfile.latest-release

services:
  - memcache
  - mysql
  - postgresql

sudo: false

before_script:
  - mysql -e 'create database identity_cache_test'
  - psql -c 'create database identity_cache_test;' -U postgres

script:
  - bundle exec rake test

cache: bundler

notifications:
  email: false
